version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
    - 8.2.0
  - dependency-name: query-string
    versions:
    - 6.14.0
  - dependency-name: react-content-loader
    versions:
    - 6.0.1
  - dependency-name: reactour
    versions:
    - 1.18.1
